// Mocks generated by Mockito 5.4.6 from annotations
// in machine_dashboard/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i11;
import 'dart:typed_data' as _i13;

import 'package:http/http.dart' as _i3;
import 'package:machine_dashboard/blocs/arc_time_metric/arc_time_metric_bloc.dart'
    as _i8;
import 'package:machine_dashboard/models/arc_time_metric.dart' as _i2;
import 'package:machine_dashboard/models/job.dart' as _i6;
import 'package:machine_dashboard/services/api_arc_time_service.dart' as _i10;
import 'package:machine_dashboard/services/api_job_service.dart' as _i9;
import 'package:machine_dashboard/services/arc_time_service.dart' as _i7;
import 'package:machine_dashboard/services/job_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArcTimeMetric_0 extends _i1.SmartFake implements _i2.ArcTimeMetric {
  _FakeArcTimeMetric_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JobService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobService extends _i1.Mock implements _i4.JobService {
  MockJobService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Job>> fetchJobs() => (super.noSuchMethod(
        Invocation.method(
          #fetchJobs,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Job>>.value(<_i6.Job>[]),
      ) as _i5.Future<List<_i6.Job>>);

  @override
  _i5.Future<void> addJob(_i6.Job? newJob) => (super.noSuchMethod(
        Invocation.method(
          #addJob,
          [newJob],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateJobStatus(
    String? jobId,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobStatus,
          [
            jobId,
            isActive,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteJob(String? jobId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJob,
          [jobId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateJob(_i6.Job? updatedJob) => (super.noSuchMethod(
        Invocation.method(
          #updateJob,
          [updatedJob],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ArcTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArcTimeService extends _i1.Mock implements _i7.ArcTimeService {
  MockArcTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ArcTimeMetric> fetchArcTime({
    required DateTime? date,
    required _i8.ArcTimeRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArcTime,
          [],
          {
            #date: date,
            #range: range,
          },
        ),
        returnValue: _i5.Future<_i2.ArcTimeMetric>.value(_FakeArcTimeMetric_0(
          this,
          Invocation.method(
            #fetchArcTime,
            [],
            {
              #date: date,
              #range: range,
            },
          ),
        )),
      ) as _i5.Future<_i2.ArcTimeMetric>);
}

/// A class which mocks [ApiJobService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiJobService extends _i1.Mock implements _i9.ApiJobService {
  MockApiJobService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Job>> fetchJobs() => (super.noSuchMethod(
        Invocation.method(
          #fetchJobs,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Job>>.value(<_i6.Job>[]),
      ) as _i5.Future<List<_i6.Job>>);

  @override
  _i5.Future<void> addJob(_i6.Job? newJob) => (super.noSuchMethod(
        Invocation.method(
          #addJob,
          [newJob],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateJobStatus(
    String? jobId,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobStatus,
          [
            jobId,
            isActive,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteJob(String? jobId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJob,
          [jobId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateJob(_i6.Job? updatedJob) => (super.noSuchMethod(
        Invocation.method(
          #updateJob,
          [updatedJob],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ApiArcTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiArcTimeService extends _i1.Mock implements _i10.ApiArcTimeService {
  MockApiArcTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ArcTimeMetric> fetchArcTime({
    required DateTime? date,
    required _i8.ArcTimeRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArcTime,
          [],
          {
            #date: date,
            #range: range,
          },
        ),
        returnValue: _i5.Future<_i2.ArcTimeMetric>.value(_FakeArcTimeMetric_0(
          this,
          Invocation.method(
            #fetchArcTime,
            [],
            {
              #date: date,
              #range: range,
            },
          ),
        )),
      ) as _i5.Future<_i2.ArcTimeMetric>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i5.Future<_i13.Uint8List>);

  @override
  _i5.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
