
/// Represents a job with various machine settings.
///
/// This model is designed to be robust, handling potentially null or missing
/// data from an API response and correctly formatting data for API submission.
class Job {
  /// The unique identifier for the job. It is nullable because when creating a
  /// new job, the ID is assigned by the server, not the client.
  final String? id;
  final String title;
  final String mode;
  final String current;
  final String hotStartTime;
  final String wave;
  final String base;
  final String pulse;
  final String duty;
  final String wire;
  final String shieldingGas;
  final String arcLength;
  final String diameter;
  final String inductance;
  bool isActive;

  Job({
    this.id, // ID is now optional.
    required this.title,
    required this.mode,
    required this.current,
    this.hotStartTime = '',
    this.wave = '',
    this.base = '',
    this.pulse = '',
    this.duty = '',
    this.wire = '',
    this.shieldingGas = '',
    this.arcLength = '',
    this.diameter = '',
    this.inductance = '',
    this.isActive = false,
  });

  /// Factory constructor to create a `Job` from a JSON map.
  ///
  /// This constructor is hardened to prevent crashes from unexpected null values
  /// in the API response by providing default empty strings.
  factory Job.fromJson(Map<String, dynamic> json) {
    return Job(
      // Use `_asString` helper to safely convert values.
      id: _asString(json['_id'] ?? json['id']), // Server might use '_id' or 'id'
      title: _asString(json['title']),
      mode: _asString(json['mode']),
      current: _asString(json['current']),
      hotStartTime: _asString(json['hotStartTime']),
      wave: _asString(json['wave']),
      base: _asString(json['base']),
      pulse: _asString(json['pulse']),
      duty: _asString(json['duty']),
      wire: _asString(json['wire']),
      shieldingGas: _asString(json['shieldingGas']),
      arcLength: _asString(json['arcLength']),
      diameter: _asString(json['diameter']),
      inductance: _asString(json['inductance']),
      isActive: json['isActive'] ?? false,
    );
  }

  /// Converts the `Job` instance to a JSON map for sending to the API.
  ///
  /// The 'id' field is intentionally excluded from the JSON payload because
  /// it should be generated by the server upon creation.
  Map<String, dynamic> toJson() {
    return {
      // The 'id' is NOT included here.
      'title': title,
      'mode': mode,
      'current': current,
      'hotStartTime': hotStartTime,
      'wave': wave,
      'base': base,
      'pulse': pulse,
      'duty': duty,
      'wire': wire,
      'shieldingGas': shieldingGas,
      'arcLength': arcLength,
      'diameter': diameter,
      'inductance': inductance,
      'isActive': isActive,
    };
  }
}

/// A private helper to safely convert any value to a String.
String _asString(dynamic value) {
  if (value == null) return '';
  return value.toString();
}